name: Java CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        jdk: [ 17 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
